name: rigid
channels:
  - conda-forge
dependencies:
  - scipy
  - numpy
  - pyamg
  - nanobind
  - matplotlib
  - numba
  - cxx-compiler
  - eigen
  - pytest
  - cmake
  - scikit-sparse>=0.5
  # development dependencies
  - clangdev
  - rattler-build