context:
  package_version: ${{ env.get("PACKAGE_VERSION") }}

package:
  name: rigidbodylight
  version: ${{ package_version }}

source:
  path: ..

build:
  number: 0
  script: $PYTHON -m pip install . -vv

requirements:
  build:
    - ${{ compiler('cxx') }}
    - cmake >=3.19
    - make
    - nanobind
    - eigen
  host:
    - python
    - scikit-build-core
    - setuptools-scm
    - pip
    - numpy >=2.0
    - nanobind
    - eigen
  run:
    - python
    - scipy
    - scikit-sparse >=0.5
    - numpy >=2.0

tests:
  - python:
      imports:
        - Rigid
      pip_check: false
  - files:
      source:
        - tests/
        - structures/
    requirements:
      run:
        - pytest
        - pyamg
    script:
      - pytest

about:
  license_file: LICENSE
  summary: A lightweight code for fluctuating rigid body dynamics at the Brownian scale.
  homepage: https://github.com/numberFactory/RigidBodyLight

extra:
  recipe-maintainers:
    - rykerfish
